version: '3.8'

services:
  flask-server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PROXY_API=${PROXY_API}
      - INTERNAL_API=${INTERNAL_API}
      - PUZZLE_KEY=${PUZZLE_KEY}
      - BOT_TOKEN=${BOT_TOKEN}
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: unless-stopped

  news-checker:
    build:
      context: .
      dockerfile: Dockerfile.news_checker
    environment:
      - PROXY_API=${PROXY_API}
      - INTERNAL_API=${INTERNAL_API}
      - PUZZLE_KEY=${PUZZLE_KEY}
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - .:/app
    restart: unless-stopped
